export default {
  "login": "getify",
  "id": 150330,
  "node_id": "MDQ6VXNlcjE1MDMzMA==",
  "avatar_url": "https://avatars.githubusercontent.com/u/150330?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/getify",
  "html_url": "https://github.com/getify",
  "followers_url": "https://api.github.com/users/getify/followers",
  "following_url": "https://api.github.com/users/getify/following{/other_user}",
  "gists_url": "https://api.github.com/users/getify/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/getify/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/getify/subscriptions",
  "organizations_url": "https://api.github.com/users/getify/orgs",
  "repos_url": "https://api.github.com/users/getify/repos",
  "events_url": "https://api.github.com/users/getify/events{/privacy}",
  "received_events_url": "https://api.github.com/users/getify/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Kyle Simpson",
  "company": "Getify Solutions",
  "blog": "http://getify.me",
  "location": "Austin, TX",
  "email": null,
  "hireable": true,
  "bio": "I like to explore JS and FP techniques. Helping build a culture of engineering excellence for my employer.",
  "twitter_username": null,
  "public_repos": 59,
  "public_gists": 384,
  "followers": 30750,
  "following": 2,
  "created_at": "2009-11-08T06:56:21Z",
  "updated_at": "2021-04-18T16:21:24Z"
}
